name: test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.34

      - run: bun install
      - run: bun test
